### ISSUE TITLE
JNI linker error 

### ISSUE THREAD

**Issue by freemo** [Syncleus/aparapi-examples#3]
When running extension - FFT I get the following exception on v1.3.2:

```java

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: com.aparapi.internal.jni.OpenCLJNI.createProgram(Lcom/aparapi/device/OpenCLDevice;Ljava/lang/String;)Lcom/aparapi/internal/opencl/OpenCLProgram;
        at com.aparapi.internal.jni.OpenCLJNI.createProgram(Native Method)
        at com.aparapi.internal.opencl.OpenCLProgram.createProgram(OpenCLProgram.java:76)
        at com.aparapi.device.OpenCLDevice.bind(OpenCLDevice.java:423)
        at com.aparapi.device.OpenCLDevice.bind(OpenCLDevice.java:351)
        at com.aparapi.examples.extension.FFTExample.main(FFTExample.java:112)
        at com.aparapi.examples.All.selected(All.java:142)
        at com.aparapi.examples.All.main(All.java:79)
        ... 6 more
```

A similar error occured when running "Convolution (OpenCL)" but not on "Convolution" (might be same?):

```java

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: com.aparapi.internal.jni.OpenCLJNI.createProgram(Lcom/aparapi/device/OpenCLDevice;Ljava/lang/String;)Lcom/aparapi/internal/opencl/OpenCLProgram;
        at com.aparapi.internal.jni.OpenCLJNI.createProgram(Native Method)
        at com.aparapi.internal.opencl.OpenCLProgram.createProgram(OpenCLProgram.java:76)
        at com.aparapi.device.OpenCLDevice.bind(OpenCLDevice.java:423)
        at com.aparapi.device.OpenCLDevice.bind(OpenCLDevice.java:351)
        at com.aparapi.examples.convolution.ConvolutionOpenCL.main(ConvolutionOpenCL.java:76)
        at com.aparapi.examples.All.selected(All.java:112)
        at com.aparapi.examples.All.main(All.java:79)
        ... 6 more
```

**Comment by freemo** [comment]
this has been resolved, closing.
