### ISSUE TITLE
Running Nbody on Linux

### ISSUE THREAD

**Issue by logip** [Syncleus/aparapi-examples#4]
Hi, 
Has anybody been able to get this example to run: com.aparapi.examples.nbody ? 
I've downloaded all the JOGL and gluegen stuff and put in the right place and now I get the following error: 

Exception in thread "main" com.jogamp.opengl.GLException: Profile GL_DEFAULT is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x0, owner false, ResourceToolkitLock[obj 0x4f063c0a, isOwner false, <1e6d1014, 76707e36>[count 0, qsz 0, owner <NULL>]]], but: []
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
	at com.jogamp.opengl.GLProfile.getDefault(GLProfile.java:722)
	at com.jogamp.opengl.GLCapabilities.<init>(GLCapabilities.java:84)
	at com.aparapi.examples.nbody.Main.main(Main.java:253)

Any ideas? Is this maybe a JOGL problem? There are more similar examples but all have the same error. 

I'm running this on a Ubuntu 16.04.2
I'm using the most recent driver from AMD on my 390 card -> amdgpu-pro-17.10-401251
I've installed the most recent AMD APP 3.0

With regards, Logi

**Comment by freemo** [comment]
@logip Sorry just saw this. Works fine here and most people have run it without issue. Since this issue is so old I'm going to close it. But please reopen it if you feel it is still relevant. I pay more attention to the issues on the core project and so I never saw this one, sorry.
